### ISSUE TITLE
file.url is slow - libcloud performs a HEAD on each file

### ISSUE THREAD

**Issue by tomkins** [pydanny-archive/dj-libcloud#16]
Related to issue #5, when using Amazon S3 as the storage backend it performs a HEAD request:

```
def url(self, name):
    provider_type = self.provider['type'].lower()
    obj = self._get_object(name)
```

I'd suggest adding another (optional) setting for each libcloud provider, something like:

```
LIBCLOUD_PROVIDERS = {
    'default': {
        ...
        'url_prefix': 'http://example.org/',
    },
}
```

If it exists, then just combine url_prefix + name to give the URL to a file. If the setting isn't added then use the old method of doing a request to figure out the URL.

**Comment by pnovotnak** [comment]
+1
